- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t jenkins1 .
      args:
        chdir: /var/lib/jenkins/workspace/jenkins1

    - name: tag image
      command: docker tag petstore:latest rajuboddu/jenkins1:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: rajuboddu
        password: dckr_pat_CUppp87mkJQdeiIHWobc-0NBH1s

    - name: Push image
      command: docker push rajuboddu/jenkins1:latest

    - name: Trivy Scan
      command: trivy image rajuboddu/jenkins1:latest > trivy.txt

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 rajuboddu/jenkins1:latest
